# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 94336c4d96b2c13b4018e58607cc10e87c8ea6248ad7e518eb7c57df8184668360af0e994ece56dc5f6b116a3a4782222bfcc99dcd4f726ea0160e2b83db7f4e

test:
  secret_key_base: 0eab8e18cfbaa0eeff80037abba063ba7e0033f75c54caf14878b14947a2649c6d50ed3f0da04fd361c250c2b869392788958dc43282e6137bcd3f0221a45471

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
